security:
    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            provider: db_provider
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                 path: /quit
                 target: /
            remember_me:
                secret: '%secret%'
                lifetime: 604800

    access_control:
        - { path: ^/status/, roles: [ROLE_MANAGER,ROLE_ADMIN] }
        - { path: ^/myreports/, roles: [ROLE_TECHNICIAN,ROLE_ADMIN] }
        - { path: ^/report/, roles: [ROLE_MANAGER,ROLE_ADMIN] }
        - { path: ^/technician, roles: [ROLE_ADMIN] }
        - { path: ^/location, roles: [ROLE_ADMIN] }

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt