security:
    providers:
        in_memory:
            memory:
                users:
                    anonym: { password: anonym1, roles: ROLE_ANONYM }
                    manager: { password: manager1, roles: ROLE_MANAGER }
                    technician: { password: technician1, roles: ROLE_TECHNICIAN }
                    admin: { password: admin1, roles: ROLE_ADMIN }

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                 path: /quit
                 target: /
            remember_me:
                secret:   '%secret%'
                lifetime: 604800

    access_control:
        - { path: ^/status/, roles: [ROLE_MANAGER,ROLE_ADMIN] }
        - { path: ^/myreports/, roles: [ROLE_TECHNICIAN,ROLE_ADMIN] }
        - { path: ^/report/, roles: [ROLE_MANAGER,ROLE_ADMIN] }
        - { path: ^/technician/, roles: [ROLE_ADMIN] }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext